import { Link } from "react-router-dom";
import { useState } from "react";
import { CheckCircle, CreditCard, LockKeyhole, Truck, ShieldCheck, ArrowLeft } from "lucide-react";
import { motion } from "framer-motion";
import { useCart } from "../context/CartContext";

const Checkout = () => {
  const { cart, cartTotal, clearCart } = useCart();
  const [submitted, setSubmitted] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", address: "", city: "", postalCode: "", payment: "Card" });
  const shipping = cartTotal >= 500 || cartTotal === 0 ? 0 : 25;
  const tax = cartTotal * 0.08;
  const total = cartTotal + shipping + tax;
  const handleChange = (e) => setForm((current) => ({ ...current, [e.target.name]: e.target.value }));
  const handleSubmit = (e) => { e.preventDefault(); clearCart(); setSubmitted(true); window.scrollTo({ top: 0, behavior: "smooth" }); };

  if (submitted) return <main className="flex min-h-[75vh] items-center justify-center px-4 py-16"><motion.div initial={{ opacity: 0, scale: .92, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} className="w-full max-w-xl border border-white/10 bg-stone-900 p-8 text-center sm:p-14"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border border-amber-400/30 bg-amber-400/10"><CheckCircle size={42} className="text-amber-400" /></div><p className="section-label mt-8">Private Order</p><h1 className="heading-lg mt-4 text-white">Order Confirmed</h1><p className="mx-auto mt-5 max-w-md text-sm leading-7 text-stone-400">Thank you for choosing LUXE. Your timepiece has been reserved and your insured delivery will be arranged shortly.</p><div className="mt-8 border-y border-white/10 py-5 text-left text-xs text-stone-500"><div className="flex justify-between"><span>Order status</span><span className="text-amber-400">Confirmed</span></div><div className="mt-3 flex justify-between"><span>Delivery</span><span className="text-white">Insured worldwide</span></div></div><Link to="/collection" className="btn-gold mt-8">Continue Shopping</Link></motion.div></main>;
  if (!cart.length) return <main className="flex min-h-[75vh] items-center justify-center px-4"><div className="text-center"><p className="section-label">Checkout</p><h1 className="heading-md mt-4 text-white">Your Cart is Empty</h1><p className="mt-4 text-sm text-stone-500">Add a timepiece before continuing to checkout.</p><Link to="/collection" className="btn-gold mt-7">Return to Collection</Link></div></main>;

  const input = "mt-2 min-h-12 w-full border border-white/10 bg-stone-950 px-4 py-3 text-sm text-white outline-none transition placeholder:text-stone-700 focus:border-amber-400";
  return <main className="mx-auto w-full max-w-6xl overflow-hidden px-4 py-10 sm:px-6 sm:py-14 lg:px-8 lg:py-16">
    <Link to="/cart" className="mb-8 inline-flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-stone-400 transition hover:text-amber-400"><ArrowLeft size={15}/> Back to Cart</Link>
    <div className="mb-10"><p className="section-label">Secure Checkout</p><h1 className="heading-lg mt-5 text-white">Complete your purchase.</h1><div className="mt-6 flex max-w-2xl items-center gap-2 text-[9px] uppercase tracking-[0.15em] text-stone-600 sm:gap-4"><span className="text-amber-400">01 Cart</span><i className="h-px flex-1 bg-white/10"/><span className="text-amber-400">02 Details</span><i className="h-px flex-1 bg-white/10"/><span>03 Confirmation</span></div></div>

    <div className="grid min-w-0 gap-8 lg:grid-cols-[minmax(0,1fr)_360px] lg:gap-10">
      <form onSubmit={handleSubmit} className="min-w-0 space-y-6">
        <section className="border border-white/10 bg-stone-900 p-5 sm:p-8"><div className="flex items-center gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-amber-400 text-xs font-bold text-black">1</span><div><p className="text-[9px] uppercase tracking-widest text-stone-500">Delivery</p><h2 className="font-display text-2xl text-white">Shipping details</h2></div></div><div className="mt-7 space-y-5"><label className="block text-[10px] uppercase tracking-widest text-stone-500">Full Name<input required minLength={2} name="name" value={form.name} onChange={handleChange} placeholder="Your full name" className={input}/></label><label className="block text-[10px] uppercase tracking-widest text-stone-500">Email<input required type="email" name="email" value={form.email} onChange={handleChange} placeholder="you@example.com" className={input}/></label><label className="block text-[10px] uppercase tracking-widest text-stone-500">Address<input required minLength={5} name="address" value={form.address} onChange={handleChange} placeholder="Street address" className={input}/></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-[10px] uppercase tracking-widest text-stone-500">City<input required name="city" value={form.city} onChange={handleChange} placeholder="City" className={input}/></label><label className="block text-[10px] uppercase tracking-widest text-stone-500">Postal Code<input required inputMode="numeric" name="postalCode" value={form.postalCode} onChange={handleChange} placeholder="Postal code" className={input}/></label></div></div></section>
        <section className="border border-white/10 bg-stone-900 p-5 sm:p-8"><div className="flex items-center gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-amber-400 text-xs font-bold text-black">2</span><div><p className="text-[9px] uppercase tracking-widest text-stone-500">Payment</p><h2 className="font-display text-2xl text-white">Payment method</h2></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3">{["Card", "PayPal", "Cash on Delivery"].map((method) => <label key={method} className={`flex min-h-16 cursor-pointer items-center justify-center border p-3 text-center text-[10px] uppercase tracking-widest transition ${form.payment === method ? "border-amber-400 bg-amber-400/5 text-amber-400" : "border-white/10 text-stone-400 hover:border-white/30"}`}><input type="radio" name="payment" value={method} checked={form.payment === method} onChange={handleChange} className="sr-only"/>{method}</label>)}</div>{form.payment === "Card" && <div className="mt-5 flex gap-3 border border-white/10 bg-black/20 p-4 text-xs leading-5 text-stone-500"><CreditCard size={18} className="mt-0.5 shrink-0 text-amber-400"/> Demo checkout — no real card details are collected.</div>}</section>
        <div className="border border-amber-400/10 bg-amber-400/[0.03] p-5 text-xs leading-5 text-stone-500"><div className="flex gap-3"><ShieldCheck size={18} className="shrink-0 text-amber-400"/><span>Your purchase is protected by LUXE authenticity assurance and insured delivery.</span></div></div>
        <button type="submit" className="btn-gold min-h-14 w-full"><LockKeyhole size={16} className="mr-3"/> Place Secure Order · ${total.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</button>
      </form>

      <aside className="h-fit min-w-0 border border-white/10 bg-stone-900 p-5 sm:p-7 lg:sticky lg:top-28"><h2 className="font-display text-2xl text-white">Order Summary</h2><div className="mt-6 max-h-80 space-y-4 overflow-y-auto pr-1">{cart.map((item) => <Link to={`/watch/${item.id}`} key={item.id} className="flex min-w-0 gap-3 group"><img src={item.image} alt={item.name} className="h-16 w-16 shrink-0 object-cover"/><div className="min-w-0 flex-1"><p className="truncate text-xs text-white group-hover:text-amber-400">{item.name}</p><p className="mt-1 text-[9px] uppercase tracking-widest text-stone-500">{item.brand} × {item.quantity}</p></div><span className="shrink-0 text-xs text-white">${(item.price * item.quantity).toLocaleString()}</span></Link>)}</div><div className="my-6 h-px bg-white/10"/><div className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-stone-500">Subtotal</span><span>${cartTotal.toFixed(2)}</span></div><div className="flex justify-between"><span className="text-stone-500">Shipping</span><span>{shipping ? `$${shipping.toFixed(2)}` : "Free"}</span></div><div className="flex justify-between"><span className="text-stone-500">Tax</span><span>${tax.toFixed(2)}</span></div><div className="my-5 h-px bg-white/10"/><div className="flex justify-between text-lg"><span>Total</span><span className="text-amber-400">${total.toFixed(2)}</span></div></div><div className="mt-7 grid gap-3 border-t border-white/10 pt-5 text-[9px] uppercase tracking-widest text-stone-500"><div className="flex items-center gap-3"><Truck size={16} className="text-amber-400"/> Insured worldwide delivery</div><div className="flex items-center gap-3"><LockKeyhole size={16} className="text-amber-400"/> Secure checkout</div></div></aside>
    </div>
  </main>;
};
export default Checkout;
